apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ms-boilerplate-backend-config-esp
spec:
  timeoutSec: 60
  securityPolicy:
    name: "ms-ca-policy"
  healthCheck:
    checkIntervalSec: 30
    port: 8080
    type: HTTP
    requestPath: /health
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ms-boilerplate-frontend-config
spec:
  sslPolicy: ms-ssl-policy